version: '4.8'
services:
  db-dev:
    image: postgres:13
    ports: 
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest_restapi
    networks:
      - freecodecamp
networks:
  freecodecamp: