services:
  db-dev:
    container_name: db-dev-postgres
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest_restapi
    networks:
      - freecodecamp
  redis-dev:
    container_name: redis-dev
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - freecodecamp
networks:
  freecodecamp:
    name: freecodecamp
